config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'products' => 'products#index'
  get 'products/create' => 'products#create'
  post 'products/store' => 'products#store'
  get 'products/:id/remove' => 'products#remove'
  get 'products/:id/edit' => 'products#edit'
  patch 'products/update' => 'products#update'
  get 'products/search' => 'products#search', as: :search_products


  root "products#index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions
  
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true	
	validates :price, numericality: true	
	validates :amount, numericality: true	
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessible :email, :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end


	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.order(:name).limit 25
	end

	def create
		@product = Product.new
	end

	def store
		product_data = params.require(:product).permit :name, :price, :amount, :description
		@product = Product.new product_data		
		if @product.save
			redirect_to "/products"
		else
			render :create
		end

	end
	

	def remove
		id = params.require(:id)
		Product.destroy id
		redirect_to "/products"
	end

	def edit
		id = params.require(:id)
		@product = Product.find_by id: id
	end

	def update
		p_data = params.require(:product).permit :name, :price, :amount, :description, :id
		product = Product.update p_data[:id], :name => p_data[:name], :price => p_data[:price], :amount => p_data[:amount], :description => p_data[:description] 
		redirect_to "/products"
	end

	def search
		@search = params[:s]
		@products = Product.where "name like ?", "%#{@search}%"
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new 
		@user = User.new
	end

	def create
		params_user = params.require(:user).permit :email, :password, :password_confirmation

		@user = User.new(params_user)
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja de camisetas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar brand: "Loja de Camisas", brand_link: root_url, reponsive: true do %>
	<%= menu_group do %>
		<%= menu_item "Home page", root_path %>
		<%= drop_down "Products" do %>
			<%= menu_item "List of products", "/products" %>
			<%= menu_item "Add a new product", "/products/create" %>
		<% end %>
	<% end %>

	<%= form_tag search_products_path, method: :get, class: "navbar-form navbar-right" do %>
		<div class="form-group">
			<%= text_field_tag :s, @search, class: "form-control" %>
			<%= button_to "Search", nil, class: "btn btn-default" %>
		</div>
	<% end %>

<% end %>

<div class="container">
	<%= yield %>
</div><!-- div.container -->

</body>
</html>

app/views/products/create.html.erb
<div class="page-header">
	<h1>Create a new product</h1>	
</div>

<% if @product.errors.full_messages.size > 0 %>
<div class="alert alert-danger" role="alert" >
	<ul>
		<% @product.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<%= form_for @product, html: {class: "form"}, url: {action: "store"} do |f| %>
	<h1 class="teste"><%= @error %></h1>	
	<div class="row">
		<div class="form-group col-md-6">
			<label>Product name:</label>
			<%= f.text_field :name, class: "form-control"%>
		</div>
	</div>
	
	<div class="row">
		<div class="form-group col-md-3">
			<label>Price:</label>
			<input class="form-control" name="product[price]" type="text" />
		</div>
		<div class="form-group col-md-3">
			<label>Amount:</label>
			<input class="form-control" name="product[amount]" type="text" />
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<label>Description:</label>
			<textarea class="form-control" name="description" rows="4"></textarea>
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<button class="btn btn-success btn-lg pull-right">Save</button>
		</div>
	</div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
	<h1>Edit a product</h1>	
</div>

<%= form_for @product, html: {class: "form"}, url: {action: "update"} do |f| %>	

	<div class="row">
		<div class="form-group col-md-6">
			<label>Product name:</label>
			<%= f.text_field :name, class: "form-control"%>
		</div>
	</div>
	
	<div class="row">
		<div class="form-group col-md-3">
			<label>Price:</label>
			<%= f.text_field :price, class: "form-control"%>
		</div>
		<div class="form-group col-md-3">
			<label>Amount:</label>
			<%= f.text_field :amount, class: "form-control"%>
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<label>Description:</label>
			<%= f.text_area :description, class: "form-control"%>
		</div>
	</div>


	<%= f.hidden_field :id %>

	<div class="row">
		<div class="form-group col-md-6">
			<button class="btn btn-success btn-lg pull-right">Update</button>
		</div>
	</div>
<% end %>

app/views/products/index.html.erb
<div class="page-header">
	<h1>Products</h1>
</div>

<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th class="text-center">Price</th>
				<th class="text-center">Amount</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td class="text-center"><%= product.price %></td>
					<td class="text-center"><%= product.amount %></td>
					<td class="text-center">

						<a href="/products/<%= product.id %>/remove" class="btn btn-default btn-xs pull-left">
							<i class="fa fa-remove"></i>
						</a>

						<a href="/products/<%= product.id %>/edit" class="btn btn-default btn-xs pull-left">
							<i class="fa fa-pencil"></i>
						</a>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/products/search.html.erb
<div class="page-header">
	<h1>Search</h1>
</div>

<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th class="text-center">Price</th>
				<th class="text-center">Amount</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td class="text-center"><%= product.price %></td>
					<td class="text-center"><%= product.amount %></td>
					<td class="text-center">

						<a href="/products/<%= product.id %>/remove" class="btn btn-default btn-xs pull-left">
							<i class="fa fa-remove"></i>
						</a>

						<a href="/products/<%= product.id %>/edit" class="btn btn-default btn-xs pull-left">
							<i class="fa fa-pencil"></i>
						</a>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>